### ISSUE TITLE
Any way to detect abscence of phantomjs binary?

### ISSUE THREAD

**Issue by thybzi** [sgentle/phantomjs-node#228]
If there is no `phantomjs` binary installed, one can see console messages like "you don't have 'phantomjs' installed".

That's really good thing to know, but I think a better option is to have some API method in your (really helpful, though!) nodejs module, that can pre-detect this problem (and so developer that uses it wouldn't try to create phantomjs window etc.)

Or maybe there is any other way to detect such kind of problem (other than reading console messages).

Thank you!

**Comment by amir20** [comment]
What happens when bin is not installed? Doesn't it just say binary file missing?

**Comment by pscollins** [comment]
Under the hood, it's just prepending an optional path to the string `'phantomjs'`:

    options.binary ?= options.path+'phantomjs'
    ...
    ps = startPhantomProcess options.binary, port, hostname, args

so you're just as well off checking for the presence of a file named "phantomjs" in your `PATH` as you are letting `phantom-node` do it for you. It would be possible to add in a `phantomBinaryExists` method, but I don't think it would be able to differentiate between a file named `phantomjs` and the real deal, so it might be misleading. 

I think the error callback is doable, though. There's currently this snippet: 

      ps.on 'error', (err) ->
        httpServer.close()
        if err?.code is 'ENOENT'
          console.error "phantomjs-node: You don't have 'phantomjs' installed"
        else
          throw err

which, as I understand, is a Bad Thing to do in nodejs world. So, in order to preserve existing code, I'm submitting a patch that calls the provided callback as `cb(result, err)` with `null` result when the operation failed and `null` err when the operation succeeded. I've written the change but I can't quite get my tests for it working -- I'll submit a pull request when I do.
